# -*- coding: utf-8 -*-
"""hay

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPNV3UISRElyrbgEGDhLxdJxrCtiVwY9
"""

print("hello world")